/* Compiled from app/src/data.jsx by app/build.js (Babel 7.29.0, preset react). Edit the .jsx, then rebuild. */
// AI Flotation token data + shared helpers (ported from source Multi-Brand Tokens project, ai-flotation only)
const AFL_BRANDS = [
{ systemId: 'ai-flotation-a', id: 'ai-flotation-a', brandId: 'ai-flotation', variant: 'a', variantLabel: 'Option A — Forge', name: 'AI Flotation', blurb: 'Workflow intake to delivered system.', mark: 'assets/ai-flotation-mark.svg',
  fonts: { heading: 'Space Grotesk', body: 'Archivo', license: 'OFL (Google Fonts)' }, typeScale: { base: 16, ratio: 1.3 }, radius: 2, shadow: '0 1px 2px rgba(20,18,16,0.30)',
  motion: { personality: 'Decisive — crisp, immediate, no flourish', duration: { fast: '80ms', base: '140ms', slow: '210ms' }, easing: { standard: 'cubic-bezier(0.3,0,0,1)', enter: 'cubic-bezier(0.16,0,0,1)', exit: 'cubic-bezier(0.4,0,1,1)' }, enterDistance: '5px', pressScale: 0.99, rules: 'fast → hover, press, toggles · base → menus, toasts, accordions · slow → modals, view changes; exits run at fast with the exit curve; prefers-reduced-motion collapses all motion' },
  modes: { light: { bg: '#F7F6F4', bgElevated: '#FFFFFF', fg: '#1A1917', fgMuted: '#56524B', accent: '#BA430E', accentContrast: '#FFFFFF', accentSoft: '#FBE4D5', line: '#DEDAD3', success: '#1F7A3D', warning: '#8F6400', danger: '#BB3131' },
    dark: { bg: '#121110', bgElevated: '#1C1A18', fg: '#EDEAE6', fgMuted: '#ADA79E', accent: '#F0813C', accentContrast: '#221206', accentSoft: '#3A2313', line: '#35322E', success: '#57BE7C', warning: '#DFA83E', danger: '#F0736B' } },
  responsive: { breakpoints: { sm: '640px', md: '768px', lg: '1024px', xl: '1280px' }, touchTargetMin: '44px', pagePadding: 'clamp(16px, 4vw, 32px)', note: 'Fluid layout: paddings clamp, grids use minmax(min(Npx,100%),1fr); display type may use clamp() between the Heading and Display steps.' } },
{ systemId: 'ai-flotation-b', id: 'ai-flotation-b', brandId: 'ai-flotation', variant: 'b', variantLabel: 'Option B — Harbor', name: 'AI Flotation', blurb: 'Workflow intake to delivered system.', mark: 'assets/ai-flotation-mark.svg',
  fonts: { heading: 'Manrope', body: 'Manrope', license: 'OFL (Google Fonts)' }, typeScale: { base: 16, ratio: 1.3 }, radius: 6, shadow: '0 1px 3px rgba(10,20,18,0.18)',
  motion: { personality: 'Decisive — crisp, immediate, no flourish', duration: { fast: '80ms', base: '140ms', slow: '210ms' }, easing: { standard: 'cubic-bezier(0.3,0,0,1)', enter: 'cubic-bezier(0.16,0,0,1)', exit: 'cubic-bezier(0.4,0,1,1)' }, enterDistance: '5px', pressScale: 0.99, rules: 'fast → hover, press, toggles · base → menus, toasts, accordions · slow → modals, view changes; exits run at fast with the exit curve; prefers-reduced-motion collapses all motion' },
  modes: { light: { bg: '#F6F8F7', bgElevated: '#FFFFFF', fg: '#14201D', fgMuted: '#4C5B57', accent: '#0E6E63', accentContrast: '#FFFFFF', accentSoft: '#D8EEE9', line: '#D6DEDB', success: '#1F7A3D', warning: '#8F6400', danger: '#BB3131' },
    dark: { bg: '#0E1413', bgElevated: '#17201E', fg: '#E9EFED', fgMuted: '#A2B1AC', accent: '#46C2AF', accentContrast: '#062B25', accentSoft: '#123B35', line: '#2C3936', success: '#57BE7C', warning: '#DFA83E', danger: '#F0736B' } },
  responsive: { breakpoints: { sm: '640px', md: '768px', lg: '1024px', xl: '1280px' }, touchTargetMin: '44px', pagePadding: 'clamp(16px, 4vw, 32px)', note: 'Fluid layout: paddings clamp, grids use minmax(min(Npx,100%),1fr); display type may use clamp() between the Heading and Display steps.' } }];

const AFL_COPY = { cta: 'Book a scoping call', inputLabel: 'Company', inputValue: 'Bayside Logistics', helpText: '30 minutes, no deck.', errLabel: 'Monthly volume', errValue: 'lots', errMsg: 'Enter a number.', badgeText: 'Build', cardTitleText: 'Workflow intake to delivered system', cardBodyText: 'We map the workflow, fix the bottleneck, and hand you a running system.', cardCta: 'See process', sample: 'Competence, shipped.', modalTitle: 'Close this intake?', modalBody: 'The scoping notes stay attached to the client record.', modalCta: 'Close intake', rows: [['Invoice OCR pipeline', 'Delivered', '11 days'], ['Dispatch board rebuild', 'In build', '60%'], ['Quote follow-up bot', 'Scoping', '—']], checkLabel: 'Include maintenance', radios: ['Fixed scope', 'Retainer'], swLabel: 'Slack updates', sliderLabel: 'Automation level', selectLabel: 'Project', crumb: 'Builds', toastMsg: 'Intake closed.', toastAction: 'Undo', tipText: 'Attached to client record', progLabel: 'Build progress', faq: [['What do we get at the end?', 'A running system in your stack, documented, with a handoff call.'], ['How long does a build take?', 'Most builds land in two to five weeks.']], chips: ['OCR', 'Dispatch', 'Quotes'] };
const AFL_LOGIN = { title: 'Client sign-in', sub: 'Build status, scoping notes and handoffs.', email: 'Company email', emailValue: 'ops@bayside.co', cta: 'Sign in', remember: 'Keep me signed in', sso: 'Continue with Google Workspace', alt: 'Not a client yet?', altLink: 'Book a scoping call', foot: 'AI Flotation LLC' };
const AFL_EMAIL = { title: 'Scoping call booked', body: '30 minutes, Thursday 2:00 CT. We will map the workflow and name the bottleneck.', cta: 'See prep notes', entity: 'AI Flotation LLC', note: 'Mark + wordmark with an accent rule on bg — spare, no banner. PNG export of the mark before send.' };
const AFL_VOICE = 'confident, spare, concrete; sells competence, not inspiration';
const AFL_UX = [
["Fitts's Law", 'Targets that are bigger and closer are faster to hit.', ['Every button and input is at least 44px tall in both directions.', 'The primary CTA repeats in the nav, at the top-right where the pointer lands.']],
["Hick's Law", 'More choices mean slower decisions.', ['One filled primary button per view; everything else is secondary or ghost.', 'Nav is capped at three links plus one CTA; direction picks are binary A/B.']],
["Jakob's Law", 'People expect your product to work like the ones they already use.', ['Conventional patterns everywhere: top nav, underlined active tab, error text under the field.', 'Modals put Cancel left of the confirming action.']],
["Miller's Law", 'Working memory holds about 7 ± 2 chunks.', ['The 11 color roles group into four families: surface, text, accent, status.', 'No nav, tab or badge group exceeds five items.']],
['Law of Proximity', 'Things that sit close together read as related.', ['Labels sit 6px from their fields; sections are separated by 26px.', 'All grouping is flex/grid gap, so spacing is systematic, not ad hoc.']],
['Von Restorff Effect', 'The one thing that differs is the one thing remembered.', ['Each direction has exactly one accent hue; it marks only the primary action and active state.', 'Danger red is reserved for destructive and error states.']],
['Aesthetic-Usability Effect', 'Interfaces that look considered feel easier to use.', ['One radius and one shadow per direction, applied uniformly to every component.', 'Palettes are tuned per mode instead of naively inverted.']],
["Tesler's Law", 'Complexity can be moved, but not removed.', ['Contrast math and mode logic live inside the tokens.', 'Page authors consume 11 semantic roles and never touch raw ramps.']],
['Doherty Threshold', 'Respond within 400ms to keep people in flow.', ['Direction and mode switches are instant client-side state changes.', 'Motion tokens cap at 210ms; nothing ever blocks input.']],
['Peak-End Rule', 'People judge an experience by its peak and its end.', ['Destructive flows end in a calm confirm modal, never a browser alert.', 'Success alerts close the loop after every submit.']]];

function aflLum(hex) {const c = hex.replace('#', '');const f = (v) => {v /= 255;return v <= 0.03928 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4);};return 0.2126 * f(parseInt(c.slice(0, 2), 16)) + 0.7152 * f(parseInt(c.slice(2, 4), 16)) + 0.0722 * f(parseInt(c.slice(4, 6), 16));}
function aflRatio(a, b) {const l1 = aflLum(a),l2 = aflLum(b);return (Math.max(l1, l2) + 0.05) / (Math.min(l1, l2) + 0.05);}
function aflRgba(hex, a) {const c = hex.replace('#', '');return 'rgba(' + parseInt(c.slice(0, 2), 16) + ',' + parseInt(c.slice(2, 4), 16) + ',' + parseInt(c.slice(4, 6), 16) + ',' + a + ')';}
function aflStack(name) {return "'" + name + "', system-ui, sans-serif";}
function aflMask(src, size, color) {return { display: 'inline-block', width: size + 'px', height: size + 'px', background: color, WebkitMaskImage: 'url(' + src + ')', maskImage: 'url(' + src + ')', WebkitMaskSize: 'contain', maskSize: 'contain', WebkitMaskRepeat: 'no-repeat', maskRepeat: 'no-repeat', WebkitMaskPosition: 'center', maskPosition: 'center', flexShrink: 0 };}
const AFL_PROMPT = 'Using the AI Flotation design system: link styles.css (CSS variables + .b-* components; dark mode via data-theme="dark" on <html>; Harbor direction via data-variant="harbor"). Fonts: Space Grotesk headings + Archivo body (Forge) or Manrope (Harbor), from Google Fonts. Reference semantic tokens (--bg, --fg, --accent, ...), never raw hex. One filled primary action per view; 44px touch targets; AA contrast is guaranteed by the tokens. Motion: --motion-fast/base/slow with --ease-* curves (.b-enter, .b-pop, .b-skeleton ready-made); respect prefers-reduced-motion. Voice: ' + AFL_VOICE + '. Build: [describe what you want].';
const AFL_HULL = 'M16 54 H104 L93 86 A60 60 0 0 1 27 86 Z',AFL_FLOAT = 'M45 30 A15 15 0 1 0 75 30 A15 15 0 1 0 45 30 Z';
function AflMark({ size = 26, hull = '#1A1917', float = '#BA430E' }) {return /*#__PURE__*/React.createElement("svg", { viewBox: "0 0 120 120", width: size, height: size, "aria-hidden": "true", style: { display: 'block', flexShrink: 0 } }, /*#__PURE__*/React.createElement("path", { d: AFL_HULL, fill: hull }), /*#__PURE__*/React.createElement("path", { d: AFL_FLOAT, fill: float }));}
Object.assign(window, { AflMark, AFL_HULL, AFL_FLOAT, AFL_BRANDS, AFL_COPY, AFL_LOGIN, AFL_EMAIL, AFL_VOICE, AFL_UX, AFL_PROMPT, aflLum, aflRatio, aflRgba, aflStack, aflMask });
